apiVersion: v1
kind: Service
metadata: 
 name: webapp-service
spec:
 selector:
  mylabelname: webapp-pod # It is selecting a pod labeled webapp-pod in the pod yaml file
 ports:
  - name: http
    port: 80 # Port number to be accessed inside of the kubernetes
    nodePort: 30080 # Port number to be accessed outside of the kubernetes
 type: NodePort # Type of service which allows to be accessed outside of the kubernetes